# Generated by Django 5.1.6 on 2025-02-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabAct1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='payment_status',
            field=models.BooleanField(default=True),
        ),
    ]
